Makefile
* Now src-d/ci supports glide if glide.lock is present.
So we are relying on it. See:
https://github.com/src-d/ci/pull/29
=> Makefile: rely on new glide support of src-d/ci

archiver.go, archiver_test.go, changes.go, common.go
Repositories with no 'master' branch were failing because, trying to get the last commit date,  we had been trying to get a master reference that does not exists.
Now the logic is a little bit different: We iterate over all hash references, getting the date of each Commit that are pointing to. We return the newest date.
References that are pointing to Tags are resolved. References pointing to Objects that are not Commits or Tags are ignored, printing a warning on logs.
Fix #72
=> Fix "reference not found error"

archiver.go, archiver_test.go, fixtures_test.go
We need to take into account the initCommit to be able to update correctly the references, not only by the reference name.
- Added a new test dropping one reference going from 9 to 8
- Ignoring archiver test due to bug in go-git: src-d/go-git#466
=> Fix updateReferences method

glide.lock, glide.yaml
This brings us:
* https://github.com/src-d/go-billy-siva/pull/12
* https://github.com/src-d/core-retrieval/pull/21
which should avoid conflicts on temporary files.
=> update to latest core-retrieval.v0

archiver.go, changes.go, changes_test.go, common.go, git.go, git_test.go, model.go, model_test.go
* Introduce a new interface Referencer to retrieve references
with implementations for *model.Repository and *git.Repository.
* Now NewChanges just takes two Referencers to compare, removing
all logic specif to database access or go-git.
=> changes: abstract away code to iterate references

archiver.go, archiver_test.go, cli/borges/consumer.go, common.go, git.go, git_test.go
* Add TemporaryCloner and TemporaryRepository abstractions
to clone a remote repository to a temporary local storage
and use it to push to different URLs.
* Fetch all references with `refs/` prefix.
=> Move code for local git repository out of Archiver 

README.md
/cc @ajnavarro @smola 
Also, consider adding `clean` to Makefile instead of requesting the user to remove `Makefile.main` and `.ci`. That's an implementation detail.
=> fix typos and grammar mistakes in README

cli/borges/consumer.go, cli/borges/main.go, cli/borges/producer.go
=> Add profiling capabilities to consumer and producer

glide.lock, glide.yaml
This fixes https://github.com/src-d/borges/issues/113
=> glide: Update go-git version

git.go, git_test.go
Now remote HEAD is fetched through  the refspec "HEAD:refs/heads/HEAD" for each repository.
```bash
➜  /tmp siva list root-repositories/d668b7841482f156c60b03cfbc93a0fdcebe1d66.siva 
-rw-rw-rw- Jul 26 14:03   23 B HEAD
-rw-rw-rw- Jul 26 14:03   20 B config
-rw-rw-rw- Jul 26 14:04  93 kB objects/pack/pack-1ae420565b6543769da850583c076476e5c1dad9.idx
-rw-rw-rw- Jul 26 14:04 710 kB objects/pack/pack-1ae420565b6543769da850583c076476e5c1dad9.pack
-rw-rw-rw- Jul 26 14:04   41 B refs/heads/HEAD/015d7ec8-05f4-d5da-aace-d7e26afa0fa0
-rw-rw-rw- Jul 26 14:04   41 B refs/heads/feature/rpm/015d7ec8-05f4-d5da-aace-d7e26afa0fa0
-rw-rw-rw- Jul 26 14:04   41 B refs/heads/master/015d7ec8-05f4-d5da-aace-d7e26afa0fa0
-rw-rw-rw- Jul 26 14:04   41 B refs/pull/1/head/015d7ec8-05f4-d5da-aace-d7e26afa0fa0 …
```
=> added refspec to fetch HEAD as refs/heads/HEAD

archiver_test.go, glide.lock, glide.yaml
To have HDFS support, we need the last core-retrieval dependency.
=> Update core-retrieval dependency

common.go, common_test.go
If searching for the repositoryID by repository urls our mention has new aliases, we should add them to the existing repository.
=> common: Update aliases if needed

git_test.go
A new PR in the basic git fixture broke tests assumptions
about references in that repository. See:
https://github.com/git-fixtures/basic/pull/2
=> fix broken tests

common_test.go, producer_test.go
ProducerSuite was still using a global database instead of a temporary
one.
=> test: ensure temporary database is used

archiver.go, archiver_test.go, cli/borges/consumer.go, cli/borges/producer.go, common.go, consumer_test.go, git.go, producer.go, producer_test.go, worker.go, worker_pool.go
* Remove notifiers: we did use them only for logging, and we did
not remove logger usage with them anyway.
* Propagate logger instances (no global logger) and defined context.
This improves log message by ensuring proper context fields are
not missing.
=> logging: propagate logger instance and context

archiver.go
With this lines of code we will able to check time spent in push to rooted repositories.
=> archiver: add logs to rooted repo code

archiver.go
Prefer git, then https, then http, then any.
This should maximimize clone speed.
=> prefer git:// endoints, closes #130

archiver.go, git.go, git_test.go
Config (URL and IsFork flag) was stored in the temporary
cloned repository, instead of the persistent rooted repository.
=> fix config storage

archiver.go, archiver_test.go, glide.lock, glide.yaml
Closes #112 
This PR introduces a mechanism to ensure fatal errors do not lead to repositories being incorrectly reprocessed. To do this, when a consumer worker receives a job, it checks if the repository has the `fetching` status. If it does, it means there was a fatal error when it started processing and returns an error, which leads to the job being rejected and it's thus sent to the dead letter queue.
Immediately after that, the worker sets the status of the repository to `fetching` if it's any other status and continues normally until the end, when the status is changed to `not_found`, `fetched` or `pending` depending on the circumstances at the end of the process.
So, after the job is process (or not, if it crashes) this are the possible statuses of a repository:
* Process crashed: …
=> set repositories as fetching until they're fully fetched

README.md, cli/borges/init.go, cli/borges/main.go, common.go, glide.lock, glide.yaml
Fixes #21 
- Added `init` command that uses `schema.Create` of core-retrieval
- Split `cmd` in two, `loggerCmd` and `cmd` which embeds `loggerCmd`. The rationale behind that is that all commands need to embed `loggerCmd` to control the log in the same way, but not all need to embed `cmd`, such as `init`. Doing so would mean `init` would have, for example, a `queue` flag that is not needed.
=> create init command to initialize database

archiver.go, archiver_test.go
Depends on #147 
We should create an issue as well to remember that we should rethink and refactor `do` of `Archiver` so it's more easy to follow. Right now, there are a lot of cases where it could go wrong and we have to be very careful to change the status at the end. (One possible solution would be a defer and setting as pending if it's not not_found or fetched).
=> ensure repository status is correctly set in all cases

changes_test.go, git.go
The roots of all the visited commits are cached so when we're
looking for the roots of other references, they don't have to be
visited yet again.
This slows down a bit the lookup for references that have commits
not yet visited, but makes the rest super fast.
A benchmark for NewChanges has been added that shows the mentioned
slowdown (which is not that big), but real usage outside tests
shows that operations that took almost ~2m now take ~1s.
=> gitReferencer: cache roots of visited commits

Dockerfile
Adding [low-overhead PID1](https://github.com/Yelp/dumb-init) instead of borges process increases ability of debugging the system.
I.e in case borges consumer process hangs - it would be possible to `kill -ABRT <borges-PID>` (which will be not 1) inside the container and get a stack dump of stalled goroutines.
=> Change PID1 in Borges container to dumb-init

fixtures_test.go, git.go, git_test.go
This fixes the problem introduce by the performance improvement in gitReferencer. While I initially only fixed it, after trying it with `rails/rails` it still took 2 hours to do this. This is because if we use the preorder iterator that comes from go-git, we can't skip branches as easily. 
Imagine we have two branches, one with a root commit and another one with 50M commits. Because the branch with the root commit has not been visited yet we can't break the iteration and we have to continue all the way until we get to it. What's the problem? That means we'll iterate over these 50M commits (and decode them) just to get to one commit.
This is why I have ditched completely the iterator from go-git and made a custom iterator implementation based on it that retrieves root commits. Since we …
=> gitReferencer: make sure no branches are skipped finding root commits

archiver.go, archiver_test.go, git.go
Closes #181 
Introduces a new `sivaLoader` to which more mappings between siva hashes and storers can be added dynamically, removing the need to install and remove a new protocol each time WithInProcRepository is called. This solves the synchronization problem of the client map in go-git, which could lead to panics because of concurrent map writes and reads.
The protocol used is `siva://[rooted repo hash]`. Note that hash is just an identifier for a concrete repository storer, it could perfectly be a random number and it would work just as fine. This is because the RootedTransactioner already returns the storer, there is no need to pass the file path in the protocol and open it again when it's already opened.
When we get rid of the config part in the git directory we might be able to move …
=> git: install only one protocol for the whole app

README.md, archiver_test.go, cli/borges/packer.go, git.go, glide.lock, glide.yaml
Related to:
* https://github.com/src-d/borges/issues/180
* https://github.com/src-d/core-retrieval/pull/41
The command `packer` has bucketing disabled. I have not added a flag for this as `consumer` uses environment variables to change this parameter. Should this use environment variable or a flag for this specific command?
=> Bucketed root repositories

archiver_test.go
Sometimes when the travis container is running in a busy node 1 second
is not enough.
=> Increase archiver timeout to fix spurious failures

git.go
Use only one level directory to store local_repos. This makes possible
to delete the whole tree.
Before it was creating directories like this:
015f923c-a989-88bd-8168-dc79dff24a9d
015f923c-a984-1fed-57ba-0e1311ae34e1
015f923c-a984-1fed-57ba-0e1311ae34e1/1510671721316442023
Now the directories only have one level:
015f923c-a996-aa5b-581a-f400ab37ffd6_1510671723291729698
015f923c-a992-9e39-42e8-30af6b8b21b7_1510671722254221984
015f923c-a990-a6bf-7776-1bb35a6f4177_1510671721920332662
=> Correctly delete local_repos temporary dirs

cli/borges/packer.go
`--profiler` option is very useful for debug and sometimes pack is more convenient to test things than a full producer consumer setup.
=> Add profiler and metrics options to pack command

archiver.go
Leaving the session opened causes problems when too many jobs a created
in a small amount of time. Each session opened creates a keepalive
goroutine and can consume all stack ("fatal: morestack on g0" error).
fixes #186
=> Explicitly close etcd lock session after each job

mentionjobiter.go
Previously when there was an error getting a new job it was retried without delay or reconnecting. Now on `ErAlreadyClosed` it retries connection (`mentionJobIter.initIter`).
Fixes #194
=> Reconnect to job iterator on error

archiver.go
Now when a namenode error is detected either at the beginning of a transaction or when it's going to be committed, there are some retries to reconnect to HDFS so the consumer can continue processing repos.
Closes #217
=> Fixed hdfs reconnection

archiver.go
Catching panics in the archiver allow us to get better information about what is failing to improve borges, and also lets the consumer continue processing repositories.
Closes #227
=> archiver recovering from panics

Gopkg.lock, Gopkg.toml, cli/borges/init.go, cli/borges/producer.go, cli/borges/republish.go, cli/borges/update.go, vendor/gopkg.in/src-d/framework.v0/.travis.yml, vendor/gopkg.in/src-d/framework.v0/queue/amqp.go, vendor/gopkg.in/src-d/framework.v0/queue/amqp_test.go, vendor/gopkg.in/src-d/framework.v0/queue/common.go, vendor/gopkg.in/src-d/framework.v0/queue/memory.go, worker.go
Added a new subcommand `republish` to the producer command to republish buried jobs:
```
Usage:
borges [OPTIONS] producer republish [republish-OPTIONS]
Help Options:
-h, --help               Show this help message
[republish command options]
--queue=         queue name (default: borges)
--loglevel=      max log level enabled (default: info)
--logfile=       path to file where logs will be stored
--metrics        expose a metrics endpoint using an HTTP server
--metrics-port=  port to bind metrics to (default: 6062)
--profiler       start CPU, memory and block profilers
--profiler-port= port to bind profiler to (default: 6061)
--priority=      priority used to enqueue jobs, goes from 0 (lowest) to :MAX: (highest)
(default: 4)
--job-retries=   number of times a falied job should be processed …
```
=> producer republish command

mentionjobiter.go, producer.go
Closes #255 
I couldn't reproduce the error, but I think it could come from an unhandled error when a job iterator is closed.
I added some logic to avoid log the same error again and again.
Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>
=> Avoid log repeated producer next job error

producer.go
I just realized that some libraries return the same instance for the same error and others libraries create a new instance for the same error, so the comparison must be done by the string error.
We have an example of this in [src-d/framework](https://github.com/src-d/framework/), where we mix errors defined with the standard "errors" library and errors defined with [src-d/go-errors](https://github.com/src-d/go-errors).
Those errors defined with the standard library always returns the same instance, while errors defined with `src-d/go-errors` return a new instance each time.
standard lib:
https://github.com/src-d/framework/blob/master/queue/common.go
go-errors lib:
https://github.com/src-d/framework/blob/master/queue/amqp.go
Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>
=> producer: check repeated errors by string

archiver.go, archiver_test.go, cli/borges/consumer.go, consumer.go, consumer_test.go, executor_test.go, worker.go, worker_pool.go
Implements some of the things in #263, but it's still missing the `Copy` thing as there's still discussion around that in https://github.com/src-d/core-retrieval/issues/57 and https://github.com/src-d/core-retrieval/issues/58.
For now this implements cancellation of the clones when a SIGTERM is received in the program and stops the consumer so more jobs can't be taken.
=> consumer: support graceful shutdown

Gopkg.lock, archiver.go
It may help with potential issues like this one: https://github.com/src-d/borges/issues/287
As support for this fix, I'm gonna write some health check scripts using glusterfs native library.
Signed-off-by: kuba-- <kuba@sourced.tech>
=> Open git repo. with retries.

storage/database.go, storage/database_test.go
Batching adds a limit that disables the index and makes the queries much slower. Order forces the use of the index.
Fixes src-d/backlog#1270
=> Add order by to force the use of index.

README.md, cli/borges/consumer.go, cli/borges/packer.go
Repository download can be memory hungry and cause OOMs if done concurrently. This change makes the default more conservative with only one worker. Also the packer command now uses one worker by default. This command is usually run in a workstation and can cause problems.
Fixes #323
=> borges: set default worker number to 1

.travis.yml
Use go 1.10 to generate binaries.
**Do not merge until just before a new release is done so all other 0.16.x releases use the same go version.**
=> Use go 1.10 to build binaries

Makefile
It makes docker images error as it generates a dynamic binary.
=> makefile: disable cgo building borges binary

lock/etcd.go
It caused an infinite recursion.
=> lock: fix bug closing etcd session

cli/borges/command.go
We use kallax to connect to the database and only postgres is
supported.
Fixes #340
=> cli: delete --database-driver option

.travis.yml
It downloads the latest release instead of master. Fixes problems when it's in development and the format of `Gopkg.lock` changes.
Fixes #315
=> travis: use ci godep

docs/using-borges/getting-started.md
Fix the wrong option for `--volume`, and a missing `\` for multiline.
=> Fix docker command in getting started

linejobiter.go
Ensure that white spaces is trimmed from the URLs read from a file. ~Please note that in my tests there is an issue where urls read from a text file have an space added to the start (this space is NOT in the text file) so there is another issue that you can add from the friction log or I could add it separately.~
Update: there is no issue, the file really had spaces at the front of each URL but Vim wasn't jumping to it when going to the next line because of my settings, I'm an idiot, still this PR has merit to make the parsing of URLs more robust.
Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>
=> Trim spaces from urls when running from file

docs/using-borges/getting-started.md, docs/using-borges/key-concepts.md
- Set the docker tag for postgress in one of the example commands to the same one used above with `docker pull`, to avoid downloading postgres twice (once for the tag, once for `latest` which is the untagged default).
- Indicate the borges consumer will pack repos with siva.
Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>
=> Two small doc improvements

docs/using-borges/configuration.md, docs/using-borges/development.md, docs/using-borges/getting-started.md
* CONFIG_ -> BORGES_
* http port for rabbitmq to 15672
* use the same name for rabbitmq container in development and getting-started guides
=> docs: update doc to new version

.travis.yml, archiver.go, archiver_test.go, common.go, storage/database.go, storage/database_test.go, storage/local.go, storage/local_test.go
If there are mentions to the init commit in any reference it checks that
the siva is not empty (contains at least one commit).
To do this two new functions are added to `RepositoryStore` interface:
* `GetRefsByInit`: Gets all references that have the provided init commit.
Still not used but will be needed soon to fix problems with missing or
broken siva files.
* `InitHasRefs`: Returns true if there's a reference with an specific init
commit. Similar to `GetRefsByInit` but faster because it only check that
at least one reference has it and does not retrieve repository data.
Note: we need an index in `Reference.Init`
Fixes: #365
=> borges: check if siva file is empty when it shouldn't

storage/local_test.go
Repositories are stored in a map so the return order is not predictable.
Example of failed test: https://travis-ci.org/src-d/borges/builds/462963323#L1051
=> storage: fix test that failed randomly

Gopkg.lock, archiver.go, archiver_fastpath.go, archiver_test.go, cli/borges/consumer.go, cli/borges/file.go, cli/borges/packer.go
When a repository has only one root and is the first one to write to it the push step can be skipped and the packfile sent as is. This makes the process quite faster at the expense of disk space.
* Rename references to add the repository ID
* Change configuration (adds repository remote)
* Delete remote "origin" used to clone the repository
* Create siva file and copy temporary repository to it
* Use copier to send the new siva file to the remote location
This process skips `RootedTransactioner` to download and upload siva files. To be able to use Copier it is added to `Archiver`.
Also moved logging of time spent to copy siva files from `pushChangesToRootedRepository` to tidy it a bit.
*a*: current version
*b*: fast path
|repo|time a|time b|size a|size b|
|--|--|--|--|--| …
=> Single root fast path

consumer.go
Some messages may be malformed and not contain a valid header. In this case the message should be skipped instead of reopening the channel.
=> borges: skip malformed messages in consumer

archiver.go
The database and its references were updated each time a new rooted repo was pushed. This created a lot of pressure to the database when several repositories with multiple rooted repos are downloaded at the same time.
=> borges: update database once per repository
