src-d/borges

- README.md
> Improve Build instructions.

- archiver.go
- archiver_test.go
> archiver: mark repositories as not found into the database.

- common.go
- glide.lock
- glide.yaml
- linejobiter.go
- mentionjobiter.go
The new Mentions model add two new fields, IsFork and Aliases. In this PR we integrate and save them into repository database.
> Integrate new Mentions model into producer

- archiver.go
- git.go
- git_test.go
Just set context.TODO() at the moment.
> use go-git contexts

- git.go
- git_test.go
`isfork` is set to `true` or `false` in each remote git config section.
The resulting remote would look as follows:
```
[remote "015da250-023c-7e4a-f9ec-c27767c3bf6d"]
url = git://some/repo.git
url = https://some/repo.git
isfork = true
```
> store IsFork option to rooted repo config

- README.md
* Cli usage and config environment variables have been documented.
* SQL statement to create `repositories` table has been updated.
> documented cli and env vars

- git.go
- glide.lock
- glide.yaml
Upgrade go-git to include https://github.com/src-d/go-git/commit/773841734e11f0f607f6b047235f8527d475538f
> upgrade go-git version

- glide.lock
- glide.yaml
This fix specifically: https://github.com/src-d/go-billy/commit/4ad79063561e7a32cc8c49a2a5f27f18aea5a33e
> upgrade go-billy for some fixes

- archiver.go
Add 2 more logs
- HDFS copy to/from
- git push
> Add finegrained push logs

- borges-consumer-profiler-service.yml
- borges-consumer.yml
- borges-producer.yml
Adding here, until we have it automated in [src-d/charts](https://github.com/src-d/charts)
> Initial k8s descriptors for Borges consumer

- README.md
> docs: how to run everything on containers

- .travis.yml
- README.md
- archiver.go
- archiver_test.go
- cli/borges/consumer.go
- cli/borges/main.go
- cli/borges/packer.go
- cli/borges/producer.go
- common.go
- common_test.go
- consumer.go
- executor.go
- executor_test.go
- git_test.go
- glide.lock
- glide.yaml
- linejobiter.go
- linejobiter_test.go
- mentionjobiter.go
- producer_test.go
- storage/database.go
- storage/database_test.go
- storage/local.go
- storage/local_test.go
- storage/repostore.go
> Packer command implementation

- archiver.go
- borges-consumer.yml
- borges-producer.yml
- cli/borges/consumer.go
- cli/borges/init.go
- cli/borges/main.go
- cli/borges/packer.go
- cli/borges/producer.go
- metrics/metrics.go
- producer.go
As suggested here: https://github.com/src-d/backlog/issues/1091#issuecomment-344233485
> metrics: add metrics for borges producer and consumer

- .travis.yml
> push latest tag as well

- glide.lock
- glide.yaml
> upgrade core-retrieval: configurable siva copy dir

- Dockerfile
> include git inside docker container

- Gopkg.lock
- README.md
- vendor/gopkg.in/src-d/core-retrieval.v0/container.go
- Updated core-retrieval dependency
- Added explanation in README about `CONFIG_ROOTED_REPOSITORIES_TEMP_DIR`
> Updated core retrieval dependency

- Gopkg.lock
- archiver.go
- archiver_test.go
- metrics/metrics.go
- vendor/gopkg.in/src-d/core-retrieval.v0/model/repository.go
- vendor/gopkg.in/src-d/core-retrieval.v0/repository/copier.go
> archiver: handle private repositories

- archiver.go
- archiver_test.go
> Fix: set status properly for failed repos

- .gitignore
@jfontan is it worth to consider adding `borges` exe. to .gitignore ?
At least this is what I had to do with my local clone.
> update gitignore (add exe file)

- cli/borges/main.go
> cli: allow json output format

- cli/borges/producer.go
> Set max priority in parameter description

- cli/borges/command.go
- cli/borges/init.go
> Deprecate log params and logrus

- archiver.go
> Print root hashes as strings instead of byte slices

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/src-d/go-queue.v1/MAINTAINERS
- vendor/gopkg.in/src-d/go-queue.v1/README.md
- vendor/gopkg.in/src-d/go-queue.v1/amqp/amqp.go
* Add logging to republish producer
* Better performance republishing jobs
Fixes #305
> Update go-queue to 1.0.2

- git.go
It closes: https://github.com/src-d/borges/issues/295
Retry fetch with force when got `git.ErrForceNeeded`
Signed-off-by: kuba-- <kuba@sourced.tech>
> Force fetch.

- Gopkg.lock
- archiver.go
- lock/common.go
- lock/etcd.go
- lock/etcd_linux_test.go
- lock/local.go
> borges: cancel operations when lease is not found

- Dockerfile
- README.md
> dockerfile: use sane defaults for many environment variables

- archiver.go
The endpoint was only logged after the repository clone ended. If there
is a problem before that there was no information to which repo a log
line belongs.
It also adds endpoint info to the final log message of the job if
available (either error or success).
```
$ LOG_LEVEL=debug go run -tags norwfs cli/borges/* pack --to siva4 -f list3 --workers=1 
[2018-08-16T11:47:50.758446877+02:00] DEBUG queueing jobs source=borges/executor.go:63
[2018-08-16T11:47:50.758463385+02:00] DEBUG starting source=borges/worker.go:47 worker=0
[2018-08-16T11:47:50.758580589+02:00] DEBUG jobs queued jobs=1 source=borges/executor.go:68
[2018-08-16T11:47:50.758663409+02:00] DEBUG job started job=01654222-5466-ad10-f8e9-a5ed927252c5 source=borges/archiver.go:102
[2018-08-16T11:47:50.758721509+02:00] DEBUG …
```
> borges: print endpoint in logs as soon as possible

- Makefile
> Makefile: remove docker env vars

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go
- vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go
- vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go
- vendor/gopkg.in/src-d/go-git.v4/repository.go
It uses a still unreleased commit
> vendor: update go-git to fix bug reading pgp signatures

- cli/borges/producer.go
> cli: set queue-priority default and description

- cli/borges/command.go
- cli/borges/consumer.go
- cli/borges/producer.go
> cli: add back --metrics parameter

- lock/etcd.go
- lock/etcd_test.go
Closes https://github.com/src-d/borges/issues/344
> Set etcd dial timeout to default (3s)

- tool/common.go
- tool/common_test.go
- tool/rebucket_test.go
- tool/set_test.go
Added missing tests to `borges-tool` libraries:
* LoadList/Hash
* Set
> More tests for tool

- Gopkg.lock
- Gopkg.toml
- cli/borges/consumer.go
- consumer.go
- vendor/gopkg.in/src-d/go-git.v4/plumbing/cache/object_lru.go
- vendor/gopkg.in/src-d/go-git.v4/remote.go
I could not find a way to test channel closing in JobIter.
Fixes #383 
Fixes #384
> Fix errors stops consumer from getting more jobs
